# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import project.posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=project.posts.models.upload_to, width_field='width')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
