# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_on',
            field=models.DateField(default=datetime.datetime(2017, 5, 10, 18, 4, 40, 230860, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
