# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import project.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170420_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=project.posts.models.upload_to, width_field='width'),
        ),
    ]
